### ISSUE TITLE
Error thrown when local bind address on client is not specified.

### ISSUE THREAD

**Issue by kyngs** [Steveice10/PacketLib#26]
Hi, when I created client and ran client.getSession().connect(); Program threw this exception:
```
[19:52:56:592] [main] [ERROR]: java.lang.IllegalArgumentException: hostname can't be null
[19:52:56:593] [main] [ERROR]: 	at java.base/java.net.InetSocketAddress.checkHost(InetSocketAddress.java:159)
[19:52:56:593] [main] [ERROR]: 	at java.base/java.net.InetSocketAddress.<init>(InetSocketAddress.java:226)
[19:52:56:593] [main] [ERROR]: 	at io.netty.util.internal.SocketUtils$10.run(SocketUtils.java:181)
[19:52:56:593] [main] [ERROR]: 	at io.netty.util.internal.SocketUtils$10.run(SocketUtils.java:178)
[19:52:56:593] [main] [ERROR]: 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
[19:52:56:593] [main] [ERROR]: 	at io.netty.util.internal.SocketUtils.socketAddress(SocketUtils.java:178)
[19:52:56:593] [main] [ERROR]: 	at io.netty.bootstrap.AbstractBootstrap.localAddress(AbstractBootstrap.java:159)
[19:52:56:594] [main] [ERROR]: 	at com.github.steveice10.packetlib.tcp.TcpClientSession$2.run(TcpClientSession.java:145)
[19:52:56:594] [main] [ERROR]: 	at com.github.steveice10.packetlib.tcp.TcpClientSession.connect(TcpClientSession.java:163)
```
When I investigated it by a bit, I've found out that this is caused by the local bind address being null, as stated in Client constructor:
```java
public Client(String host, int port, PacketProtocol protocol, SessionFactory factory) {
        this(host, port, null, 0, protocol, factory);
}
```
Am I doing something wrong? If yes, what?

**Comment by Steveice10** [comment]
Can you check if this is fixed by https://github.com/Steveice10/PacketLib/commit/09d7774037d3b7eed98b5df4af900a9f5f1dc4ac

**Comment by kyngs** [comment]
Seems to work, thanks for your time.
