### ISSUE TITLE
IndexOutOfBoundsException: readerIndex(32) + length(4) exceeds writerIndex(32)

### ISSUE THREAD

**Issue by kyngs** [Steveice10/PacketLib#27]
Hi, when reading int, packetlib throws an exception:
```
[21:55:45:126] [nioEventLoopGroup-3-2] [ERROR]: java.lang.IndexOutOfBoundsException: readerIndex(32) + length(4) exceeds writerIndex(32): PooledUnsafeDirectByteBuf(ridx: 32, widx: 32, cap: 32)
[21:55:45:127] [nioEventLoopGroup-3-2] [ERROR]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1478)
[21:55:45:127] [nioEventLoopGroup-3-2] [ERROR]: 	at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:811)
[21:55:45:127] [nioEventLoopGroup-3-2] [ERROR]: 	at com.github.steveice10.packetlib.tcp.io.ByteBufNetInput.readInt(ByteBufNetInput.java:51)
[21:55:45:127] [nioEventLoopGroup-3-2] [ERROR]: 	at org.okbot.discord.jda.net.packets.server.SPacketData.read(SPacketData.java:50)
[21:55:45:127] [nioEventLoopGroup-3-2] [ERROR]: 	at com.github.steveice10.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:59)
Shortened, because it is a huge stack trace, full trace here: https://bin.kyngs.xyz/xovibigoji.md
```
For some reason it only happens in such a specific case, here is the code for reading and writing data:
```java
    @Override
    public void read(NetInput in) throws IOException{
        slaves = new HashSet<>();
        for (int i = 0; i < in.readInt(); i++) {
            slaves.add(new ChatSlave(in.readString(), in.readInt(), in.readBoolean(), in.readInt()));
        }
        yourId = in.readInt();
        idOfNext = in.readInt();  //Exception occurs here
    }

    @Override
    public void write(NetOutput out) throws IOException {
        out.writeInt(slaves.size() - 1);
        for (Slave slave : slaves) {
            if (slave.getId() == yourId) continue;
            out.writeString(slave.getHost());
            out.writeInt(slave.getPort());
            out.writeBoolean(slave.isReady());
            out.writeInt(slave.getId());
        }
        out.writeInt(yourId);
        out.writeInt(idOfNext);
    }
```
I really apologize if I am doing something wrong, however, I checked it like 100 times and I cannot still find the problem.

**Comment by Steveice10** [comment]
On this line:
```
        for (int i = 0; i < in.readInt(); i++) {
```

You should be saving the value of in.readInt() into a variable and referencing that. Otherwise, you'll be reading another int every time it loops and performs the check.

**Comment by kyngs** [comment]
Oh no I am dumb, sorry for wasting your time, gonna check it, if it would work (I think it will), I will close this issue.

**Comment by kyngs** [comment]
As expected, it works.
