### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by ensirius** [Steveice10/PacketLib#8]
I am getting sometimes this exception. 

```java
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:886)
	at java.util.ArrayList$Itr.next(ArrayList.java:836)
	at org.spacehq.packetlib.tcp.TcpSession.callEvent(TcpSession.java:160)
	at org.spacehq.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:44)
	at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:227)
	... 26 more
```

**Comment by Steveice10** [comment]
https://github.com/Steveice10/PacketLib/commit/aa1c3051a927b9c91814c7b80081a6f5c1e012f8

**Comment by ensirius** [comment]
How i can update packet lib if i am using mcprotocol?

**Comment by Steveice10** [comment]
When PacketLib is updated, MCProtocolLib is rebuilt with the latest build.

**Comment by ensirius** [comment]
http://repo.spacehq.org/content/repositories/snapshots/org/spacehq/mcprotocollib/

Doesnt looks so :( Sorry for nagging you.

**Comment by Steveice10** [comment]
It's definitely there now.
